apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  template:
    spec:
      containers:
        - name: server
          env:
          - name: CORS_ORIGIN
            value: http://client-product-catalog-dev.<your-wildcard>
          image: quay.io/<your-repo>/server:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  template:
    spec:
      containers:
        - name: client
          image: quay.io/<your-repo>/client:latest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client
data:
  config.js: |-
    window.ENV = {
      "API_URL":"http://server-product-catalog-dev.<your-wildcard>",
      "API_KEY":"	43fbc9b33302db65d58553e27d1679ac"
    }