apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- https://github.com/masauve/product-catalog/environments/overlays/tools/argocd/apps
- https://github.com/masauve/product-catalog/environments/overlays/tools/argocd/manager


patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-dev
  path: patch-dev-app.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-test
  path: patch-test-app.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-prod
  path: patch-prod-app.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-cicd
  path: patch-cicd-app.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-monitor
  path: patch-monitor-app.yaml