apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCnV10rC8gcTnj1o4Rwr6idI9AmLHy90wnOipw4WiUHkjIHYWgs7s3Hklf8iBlh2i7ztkqMbpgME00EINX0bbZTjQ4r19gbz2Zk92LAXjxu6FlOhjA6SZqWF0yPH4Zu7hBqAdX7mWDlqRl36jEEk3KFs0NGzcYqUAxQjwY6MOhWZKyX7+Q8alTMiZQAAQ1i8FvD/XjwGo2hqoKeQF+9C3Ky2nDhyqfeTUOq+dvwPZomVXRs/3BZ5MTBhNUIXike8AiQZqwh0HvJ+cBm/5OfU0OvU6WLxszgZ0RZJ+nkiHhn9Zu8weVYlrh4586cGMnWX8iOyKNxQPI6yImI1z20Lo73iAqtWJgK56VBNAm/+thOUwtSwDK20HQvcqKV2iz2HIirwDcO5Knu0UBFPFwVHAxr6iigfe5dnVgX349UKZHsgis655eMXgjinEctH878cWlzvKNKj13GF+9D7pK/LQRZQ0AJu/JA0VBvLR3LX6oD8GOXx2i8B4cl0S9d/Sh3buOno+xdT9J5e6TLrqLh/MSIYI2PAnmXD1q1K4CYL8ggmX3oRJqnQfEAiim93351kAEtBwTK7bIaXvxxlEttnhCcmu98Em88/VweJ9mRTVMkPno6flbBbMOU+x1hCNYGAeJlleJpxzYK7k5tjKq4QQnrRsPdPLa0PNZxnqDFshAO/cZjJxmZ1OVcNHeXZXjVwT7kczV998O4hVv6bAgFGi+Z3FtOS0GkszzxF0yQpe4Pc0WFKSth4VCDujLSbqg0QNhtyG4lA3tEO+xRCVphr7PNeDPAlGmY4/YHW5NY8seIoM/Td0h2c8vr9S7iu6P0+LPxh9wtNoK3W6yjZIXI8P64yjueV1O0kQkKMpMgcL+itg==
  template:
    metadata:
      creationTimestamp: null
      name: dest-docker-config
      namespace: argocd
    type: kubernetes.io/dockerconfigjson
status: {}

